name: Reusable Test Runner (with uv)

on:
  workflow_call:
    inputs:
      server_path:
        required: true
        type: string

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.server_path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run Tests
        run: uv run pytest --cov=${{ inputs.code_path }} --cov-fail-under=60
