name: Test Slack Server

on:
  push:
    paths:
      - "servers/slack/**"
  pull_request:
    paths:
      - "servers/slack/**"

jobs:
  test:
    uses: ./.github/workflows/run-server-tests.yml
    with:
      server_path: servers/slack
